/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interfaz.java
 *
 * Created on 16/06/2010, 04:16:14 PM
 */
package simuladorcolas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import simuladorcolas.Simulador.Cliente;
import java.util.concurrent.Semaphore;

/**
 *
 * @author a64799
 */
public class Interfaz extends javax.swing.JFrame {

    int contadorDentro = 0;

    public void Actualizar(ArrayList<Cliente> cola) {
        Graphics g = dibujo.getGraphics();
        g.clearRect(0, 0, dibujo.getWidth(), dibujo.getHeight());
        int pos = 0;
        int tam = 10;
        for (Iterator<Cliente> it = cola.iterator(); it.hasNext();) {
            Cliente cliente = it.next();
            if (pos + tam <= dibujo.getWidth()) {
                if (cliente.getTipo() == Cliente.TIPO.UNO) {
                    g.setColor(Color.RED);
                    g.fillOval(pos, 0, tam, tam);
                } else {
                    if (cliente.getTipo() == Cliente.TIPO.DOS) {
                        g.setColor(Color.BLUE);
                        g.fillOval(pos, 0, tam, tam);
                    } else {
                        if (cliente.getTipo() == Cliente.TIPO.TRES) {
                            g.setColor(Color.YELLOW);
                            g.fillOval(pos, 0, tam, tam);
                        }
                    }
                }
                pos += tam;
            }
        }
    }

    public int getContadorDentro() {

        return contadorDentro;

    }

    public void setContadorDentro(int contadorDentro) {
        this.contadorDentro = contadorDentro;
    }

    public int getContadorEspera() {
        return contadorEspera;
    }

    public void setContadorEspera(int contadorEspera) {
        this.contadorEspera = contadorEspera;
    }
    int contadorEspera = 0;

    /** Creates new form Interfaz */
    public Interfaz() {
        initComponents();
        this.setResizable(false);

        // Se obtienen las dimensiones en pixels de la pantalla.
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Una cuenta para situar la ventana en el centro de la pantalla.
        setLocation((pantalla.width - getSize().width) / 2,
                (pantalla.height - getSize().height) / 2);
        this.mutex = new Semaphore(1); //solo se ocupa un permiso (el de simulador) para avanzar
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comenzarSimul = new javax.swing.JButton();
        detenerSimul = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cantDentro = new javax.swing.JLabel();
        cantEspera = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dibujo = new java.awt.Canvas();
        jButton1 = new javax.swing.JButton();
        panelAjustes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comenzarSimul.setText("Simular");
        comenzarSimul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarSimulActionPerformed(evt);
            }
        });

        detenerSimul.setText("Detener");
        detenerSimul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerSimulActionPerformed(evt);
            }
        });

        jLabel3.setText("cantidad dentro:");

        jLabel6.setText("cantidad espera:");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelAjustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelAjustesLayout = new javax.swing.GroupLayout(panelAjustes);
        panelAjustes.setLayout(panelAjustesLayout);
        panelAjustesLayout.setHorizontalGroup(
            panelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        panelAjustesLayout.setVerticalGroup(
            panelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantEspera)
                            .addComponent(cantDentro)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dibujo, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(29, 29, 29)
                                .addComponent(comenzarSimul)
                                .addGap(18, 18, 18)
                                .addComponent(detenerSimul)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)))
                            .addComponent(panelAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(panelAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jButton1)
                            .addComponent(comenzarSimul)
                            .addComponent(detenerSimul))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantDentro)
                .addGap(0, 0, 0)
                .addComponent(cantEspera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarSimulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarSimulActionPerformed
        setContadorDentro(getContadorDentro() + 1);
        setContadorEspera(getContadorEspera() + 1);
        cantDentro.setText(Integer.toString(+getContadorDentro()));
        cantEspera.setText(Integer.toString(getContadorEspera()));

    }//GEN-LAST:event_comenzarSimulActionPerformed

    private void detenerSimulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerSimulActionPerformed
        setContadorDentro(getContadorDentro() - 1);
        setContadorEspera(getContadorEspera() - 1);
        cantDentro.setText("" + getContadorDentro());
        cantEspera.setText("" + getContadorEspera());
    }//GEN-LAST:event_detenerSimulActionPerformed
    /**
     * Redibuja en la pizarra (this.pizarra) según el contenido de
     * this.simulador.getCola()
     */
    private void repintar()
    {
        //TODO jorge programa esto
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Cliente> lista = new ArrayList<Cliente>();
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        Actualizar(lista);

    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantDentro;
    private javax.swing.JLabel cantEspera;
    private javax.swing.JButton comenzarSimul;
    private javax.swing.JButton detenerSimul;
    private java.awt.Canvas dibujo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelAjustes;
    // End of variables declaration//GEN-END:variables
    private Semaphore mutex;
}
