/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interfaz.java
 *
 * Created on 16/06/2010, 04:16:14 PM
 */

package simuladorcolas;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author a64799
 */
public class Interfaz extends javax.swing.JFrame {
    int contadorDentro = 0;

    public int getContadorDentro() {
        return contadorDentro;
    }

    public void setContadorDentro(int contadorDentro) {
        this.contadorDentro = contadorDentro;
    }

    public int getContadorEspera() {
        return contadorEspera;
    }

    public void setContadorEspera(int contadorEspera) {
        this.contadorEspera = contadorEspera;
    }
    int contadorEspera = 0;
    /** Creates new form Interfaz */
    public Interfaz() {
        initComponents();
        this.setResizable(false);
        // Se obtienen las dimensiones en pixels de la pantalla.
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Una cuenta para situar la ventana en el centro de la pantalla.
        setLocation((pantalla.width  - getSize().width) / 2,
                    (pantalla.height - getSize().height)/ 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comenzarSimul = new javax.swing.JButton();
        detenerSimul = new javax.swing.JButton();
        porcentajeLleno = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantDentro = new javax.swing.JLabel();
        cantEspera = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comenzarSimul.setText("Simular");
        comenzarSimul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarSimulActionPerformed(evt);
            }
        });

        detenerSimul.setText("Detener");
        detenerSimul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerSimulActionPerformed(evt);
            }
        });

        jLabel1.setText("entradas");

        jLabel2.setText("salidas");

        jLabel3.setText("cantidad dentro:");

        jLabel6.setText("cantidad espera:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comenzarSimul)
                        .addGap(18, 18, 18)
                        .addComponent(detenerSimul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantEspera)
                            .addComponent(cantDentro)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(porcentajeLleno, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comenzarSimul)
                                    .addComponent(detenerSimul)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(cantDentro))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cantEspera))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel6))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(porcentajeLleno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarSimulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarSimulActionPerformed
        setContadorDentro(getContadorDentro()+1);
        setContadorEspera(getContadorEspera()+1);
        cantDentro.setText(""+getContadorDentro());
        cantEspera.setText(""+getContadorEspera());

    }//GEN-LAST:event_comenzarSimulActionPerformed

    private void detenerSimulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerSimulActionPerformed
        setContadorDentro(getContadorDentro()-1);
        setContadorEspera(getContadorEspera()-1);
        cantDentro.setText(""+getContadorDentro());
        cantEspera.setText(""+getContadorEspera());
    }//GEN-LAST:event_detenerSimulActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantDentro;
    private javax.swing.JLabel cantEspera;
    private javax.swing.JButton comenzarSimul;
    private javax.swing.JButton detenerSimul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar porcentajeLleno;
    // End of variables declaration//GEN-END:variables

}
