/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interfaz.java
 *
 * Created on 16/06/2010, 04:16:14 PM
 */
package simuladorcolas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import simuladorcolas.Simulador.Cliente;

/**
 *
 * @author a64799
 */
public class Interfaz extends javax.swing.JFrame {

    int contadorDentro = 0;

    public void Actualizar(ArrayList<Cliente> cola) {
        Graphics g = dibujo.getGraphics();
        g.clearRect(0, 0, dibujo.getWidth(), dibujo.getHeight());
        int pos = 0;
        int tam = 10;
        for (Iterator<Cliente> it = cola.iterator(); it.hasNext();) {
            Cliente cliente = it.next();
            if (pos + tam <= dibujo.getWidth()) {
                if (cliente.getTipo() == Cliente.TIPO.UNO) {
                    g.setColor(Color.RED);
                    g.fillOval(pos, 0, tam, tam);
                } else {
                    if (cliente.getTipo() == Cliente.TIPO.DOS) {
                        g.setColor(Color.BLUE);
                        g.fillOval(pos, 0, tam, tam);
                    } else {
                        if (cliente.getTipo() == Cliente.TIPO.TRES) {
                            g.setColor(Color.YELLOW);
                            g.fillOval(pos, 0, tam, tam);
                        }
                    }
                }
                pos += tam;
            }
        }
    }

    public int getContadorDentro() {

        return contadorDentro;

    }

    public void setContadorDentro(int contadorDentro) {
        this.contadorDentro = contadorDentro;
    }

    public int getContadorEspera() {
        return contadorEspera;
    }

    public void setContadorEspera(int contadorEspera) {
        this.contadorEspera = contadorEspera;
    }
    int contadorEspera = 0;

    /** Creates new form Interfaz */
    public Interfaz() {
        initComponents();
        this.setResizable(false);

        // Se obtienen las dimensiones en pixels de la pantalla.
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Una cuenta para situar la ventana en el centro de la pantalla.
        setLocation((pantalla.width - getSize().width) / 2,
                (pantalla.height - getSize().height) / 2);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comenzarSimul = new javax.swing.JButton();
        detenerSimul = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantDentro = new javax.swing.JLabel();
        cantEspera = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dibujo = new java.awt.Canvas();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comenzarSimul.setText("Simular");
        comenzarSimul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarSimulActionPerformed(evt);
            }
        });

        detenerSimul.setText("Detener");
        detenerSimul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerSimulActionPerformed(evt);
            }
        });

        jLabel1.setText("entradas");

        jLabel2.setText("salidas");

        jLabel3.setText("cantidad dentro:");

        jLabel6.setText("cantidad espera:");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantEspera)
                            .addComponent(cantDentro)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(comenzarSimul)
                        .addGap(18, 18, 18)
                        .addComponent(detenerSimul)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comenzarSimul)
                        .addComponent(detenerSimul)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantDentro)
                .addGap(0, 0, 0)
                .addComponent(cantEspera)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarSimulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarSimulActionPerformed
        setContadorDentro(getContadorDentro() + 1);
        setContadorEspera(getContadorEspera() + 1);
        cantDentro.setText(Integer.toString(+getContadorDentro()));
        cantEspera.setText(Integer.toString(getContadorEspera()));

    }//GEN-LAST:event_comenzarSimulActionPerformed

    private void detenerSimulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerSimulActionPerformed
        setContadorDentro(getContadorDentro() - 1);
        setContadorEspera(getContadorEspera() - 1);
        cantDentro.setText("" + getContadorDentro());
        cantEspera.setText("" + getContadorEspera());
    }//GEN-LAST:event_detenerSimulActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Cliente> lista = new ArrayList<Cliente>();
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.DOS));
        lista.add(new Cliente(Cliente.TIPO.TRES));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        lista.add(new Cliente(Cliente.TIPO.UNO));
        Actualizar(lista);

    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantDentro;
    private javax.swing.JLabel cantEspera;
    private javax.swing.JButton comenzarSimul;
    private javax.swing.JButton detenerSimul;
    private java.awt.Canvas dibujo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
